/**
 * Canvas-based image pipeline — convert any raster image to WebP in the
 * browser before upload. Runs on the main thread (acceptable for images
 * ≤10 MB; bigger files are rejected up front to avoid OOM on mobile).
 *
 * WebP encoder is the browser's native implementation:
 *   - Chrome 32+  ✓  Safari 16+ ✓  Firefox 65+ ✓  Edge 18+ ✓
 * Quality 0.9 is visually lossless for photos and typically cuts size
 * 50-70 % versus JPEG at the same perceived quality.
 *
 * Resolution is capped by the caller's `maxEdge` (see MAX_EDGE). Omit it
 * and the original resolution is preserved. This used to have no cap at
 * all, which meant a 4032x3024 phone photo was stored at 4032x3024 and
 * served 1:1 into a 40px avatar — every `<Image>` rendering user content
 * passes `unoptimized`, so upload is the ONLY place resolution can be
 * capped. Cropping is a separate step (applyCropToImage) that happens
 * before conversion when the caller opts in.
 *
 * **Privacy side-effect:** Canvas drawImage copies ONLY pixel data, not
 * metadata. GPS coordinates, camera serial, thumbnails, XMP, and other
 * EXIF tags from JPEG / WebP phone photos are dropped here. The WebP
 * output generated by canvas.toBlob has no EXIF chunk. We therefore
 * re-encode EVEN pre-existing WebP input (no short-circuit) so an
 * uploaded-from-phone .webp with embedded GPS still lands metadata-
 * clean in storage.
 */

export const MAX_CONVERT_BYTES = 10 * 1024 * 1024; // 10 MB image cap
export const MAX_DOC_BYTES = 50 * 1024 * 1024;     // 50 MB PDF cap
export const WEBP_QUALITY = 0.9;

/**
 * Longest-edge caps per use-case, in device pixels. Each is the largest
 * size that surface ever actually renders at, times a DPR headroom:
 *
 *   avatar  512  — public hero renders 128 CSS px; 128 x DPR 3 = 384
 *   cvPhoto 768  — print, not screen: 40mm at html2canvas scale 3 = 454
 *   media  1600  — portfolio detail asks for 720 CSS px at DPR 2 = 1440
 *   ocrPage 1400 — not a display size: A4 at 1400px is ~169 DPI, over
 *                  the ~150 DPI floor where text OCR starts failing
 *
 * The library picker lets a stored blob become a CV photo or a portfolio
 * cover later, so library uploads take `media` — the loosest downstream
 * cap — rather than their own grid's much smaller size.
 */
export const MAX_EDGE = {
  avatar: 512,
  cvPhoto: 768,
  media: 1600,
  ocrPage: 1400,
} as const;

/**
 * Scale (w,h) so the longer edge is at most `maxEdge`. Never upscales,
 * never returns a zero dimension (a canvas of width 0 throws on encode).
 */
export function fitWithin(
  w: number,
  h: number,
  maxEdge?: number,
): { w: number; h: number } {
  const longest = Math.max(w, h);
  if (!maxEdge || longest <= maxEdge) {
    return { w: Math.round(w), h: Math.round(h) };
  }
  const k = maxEdge / longest;
  return { w: Math.max(1, Math.round(w * k)), h: Math.max(1, Math.round(h * k)) };
}

/** Server-accepted MIMEs — matches convex/files.ts ALLOWED_*_TYPES.
 *  Client converts everything in CONVERTIBLE_IMAGE_TYPES to webp
 *  before upload, so only these two land in storage. */
export const SERVER_ALLOWED_TYPES = ["image/webp", "application/pdf"] as const;

// Inputs the converter knows how to read. Canvas + createImageBitmap
// handle these; animated GIF would drop all frames except the first,
// so we reject it explicitly rather than silently de-animate.
export const CONVERTIBLE_IMAGE_TYPES = [
  "image/jpeg",
  "image/jpg",
  "image/png",
  "image/webp",
] as const;

export type ConvertibleImageType = (typeof CONVERTIBLE_IMAGE_TYPES)[number];

export function isConvertibleImage(type: string): type is ConvertibleImageType {
  return (CONVERTIBLE_IMAGE_TYPES as readonly string[]).includes(type);
}

function renameToWebp(originalName: string): string {
  const base = originalName.replace(/\.(jpe?g|png|gif|bmp|webp|avif)$/i, "");
  return `${base || "image"}.webp`;
}

async function canvasToWebpBlob(canvas: HTMLCanvasElement): Promise<Blob> {
  const blob = await new Promise<Blob | null>((resolve) =>
    canvas.toBlob(resolve, "image/webp", WEBP_QUALITY),
  );
  if (!blob) throw new Error("Gagal mengonversi gambar ke WebP");
  return blob;
}

async function loadBitmap(file: File): Promise<ImageBitmap> {
  try {
    return await createImageBitmap(file);
  } catch {
    throw new Error("Gambar tidak bisa dibaca. Pastikan file tidak rusak.");
  }
}

/**
 * Convert any convertible image to WebP at original resolution. Returns
 * a new File object with .webp extension + `image/webp` MIME so the
 * downstream uploader can pass it straight to Convex storage.
 *
 * Throws (Indonesian) on:
 *   - unsupported input MIME
 *   - file larger than 10 MB (can't safely decode on mobile)
 *   - decode / encode failure
 */
export async function convertImageToWebP(
  file: File,
  maxEdge?: number,
): Promise<File> {
  if (!isConvertibleImage(file.type)) {
    throw new Error(
      "Tipe gambar tidak didukung. Gunakan JPG, PNG, atau WebP.",
    );
  }
  if (file.size > MAX_CONVERT_BYTES) {
    throw new Error(
      "Gambar terlalu besar untuk dikonversi (maks 10 MB). Kompres dulu atau pilih gambar lebih kecil.",
    );
  }

  // No short-circuit for existing WebP — re-encode to strip any EXIF /
  // XMP metadata the source may contain (GPS, camera serial, etc.).
  // Canvas drawImage carries pixels only; the output WebP is clean.

  const bitmap = await loadBitmap(file);
  try {
    const { w, h } = fitWithin(bitmap.width, bitmap.height, maxEdge);
    const canvas = document.createElement("canvas");
    canvas.width = w;
    canvas.height = h;
    const ctx = canvas.getContext("2d");
    if (!ctx) throw new Error("Canvas tidak tersedia di browser ini");
    // Required, not cosmetic: a single-step 4032 -> 512 downscale is a
    // 7.9x reduction, which aliases visibly at the browser default.
    ctx.imageSmoothingQuality = "high";
    ctx.drawImage(bitmap, 0, 0, w, h);

    const blob = await canvasToWebpBlob(canvas);
    return new File([blob], renameToWebp(file.name), {
      type: "image/webp",
      lastModified: Date.now(),
    });
  } finally {
    bitmap.close();
  }
}

/**
 * Apply a pixel-space crop rectangle to an image, returning a WebP File.
 * Input `pixelCrop` must be in the source image's coordinate system
 * (matches react-easy-crop's `croppedAreaPixels` output).
 */
export async function applyCropToImage(
  file: File,
  pixelCrop: { x: number; y: number; width: number; height: number },
  maxEdge?: number,
): Promise<File> {
  if (!isConvertibleImage(file.type)) {
    throw new Error("Tipe gambar tidak didukung untuk crop");
  }
  if (file.size > MAX_CONVERT_BYTES) {
    throw new Error(
      "Gambar terlalu besar untuk diproses (maks 10 MB). Kompres dulu.",
    );
  }
  if (
    !Number.isFinite(pixelCrop.width) ||
    !Number.isFinite(pixelCrop.height) ||
    pixelCrop.width <= 0 ||
    pixelCrop.height <= 0
  ) {
    throw new Error("Area crop tidak valid");
  }

  const bitmap = await loadBitmap(file);
  try {
    // `pixelCrop` stays in SOURCE coordinates — only the destination
    // shrinks. Scaling the source rect would crop the wrong region.
    const { w, h } = fitWithin(pixelCrop.width, pixelCrop.height, maxEdge);
    const canvas = document.createElement("canvas");
    canvas.width = w;
    canvas.height = h;
    const ctx = canvas.getContext("2d");
    if (!ctx) throw new Error("Canvas tidak tersedia di browser ini");
    ctx.imageSmoothingQuality = "high";
    ctx.drawImage(
      bitmap,
      pixelCrop.x,
      pixelCrop.y,
      pixelCrop.width,
      pixelCrop.height,
      0,
      0,
      w,
      h,
    );
    const blob = await canvasToWebpBlob(canvas);
    return new File([blob], renameToWebp(file.name), {
      type: "image/webp",
      lastModified: Date.now(),
    });
  } finally {
    bitmap.close();
  }
}

// describeConversion moved to shared/lib/formatFileSize.ts (single
// source of truth for byte formatting). Re-exported here for
// backward compatibility with existing callers.
export { describeConversion } from "./formatFileSize";
