import type { Doc } from "../_generated/dataModel";

type JobListing = Doc<"jobListings">;

const now = Date.now();
const day = 24 * 60 * 60 * 1000;

export const SEED_JOBS: ReadonlyArray<Omit<JobListing, "_id" | "_creationTime">> = [
  {
    title: "Senior Frontend Engineer",
    company: "Tokopedia",
    location: "Jakarta",
    workMode: "hybrid",
    employmentType: "full-time",
    seniority: "senior",
    salaryMin: 35_000_000,
    salaryMax: 55_000_000,
    currency: "IDR",
    description:
      "Bangun antarmuka web untuk 150+ juta pengguna Tokopedia. Fokus pada performa, aksesibilitas, dan scalability. Kolaborasi erat dengan tim desain dan backend.",
    requiredSkills: ["React", "TypeScript", "Next.js", "Performance"],
    postedAt: now - 1 * day,
    applyUrl: "https://tokopedia.com/careers",
    companyLogo: "🛍️",
  },
  {
    title: "Product Designer",
    company: "Gojek",
    location: "Jakarta",
    workMode: "onsite",
    employmentType: "full-time",
    seniority: "mid-level",
    salaryMin: 18_000_000,
    salaryMax: 30_000_000,
    currency: "IDR",
    description:
      "Desain pengalaman multi-produk (Ride, Food, Pay) untuk pengguna Asia Tenggara. Portfolio case study wajib ada.",
    requiredSkills: ["Figma", "User Research", "Design Systems", "Prototyping"],
    postedAt: now - 2 * day,
    applyUrl: "https://gojek.com/careers",
    companyLogo: "🛵",
  },
  {
    title: "Backend Engineer",
    company: "Shopee",
    location: "Remote",
    workMode: "remote",
    employmentType: "full-time",
    seniority: "mid-level",
    salaryMin: 22_000_000,
    salaryMax: 40_000_000,
    currency: "IDR",
    description:
      "Skalakan layanan marketplace yang meng-handle ribuan order per detik. Microservices, observability, cost engineering.",
    requiredSkills: ["Go", "PostgreSQL", "Kafka", "Kubernetes"],
    postedAt: now - 3 * day,
    applyUrl: "https://shopee.com/careers",
    companyLogo: "🧡",
  },
  {
    title: "Data Analyst",
    company: "Traveloka",
    location: "Jakarta",
    workMode: "hybrid",
    employmentType: "full-time",
    seniority: "entry-level",
    salaryMin: 10_000_000,
    salaryMax: 18_000_000,
    currency: "IDR",
    description:
      "Bantu tim produk memahami perilaku pengguna travel. SQL, dashboard, A/B testing.",
    requiredSkills: ["SQL", "Python", "Looker", "Statistics"],
    postedAt: now - 4 * day,
    applyUrl: "https://traveloka.com/careers",
    companyLogo: "✈️",
  },
  {
    title: "Full-stack Engineer (React + Node)",
    company: "Startup.id",
    location: "Bandung",
    workMode: "remote",
    employmentType: "contract",
    seniority: "mid-level",
    salaryMin: 15_000_000,
    salaryMax: 28_000_000,
    currency: "IDR",
    description:
      "Startup tahap awal butuh engineer serba-bisa. Ship feature end-to-end dari DB sampai UI.",
    requiredSkills: ["React", "Node.js", "TypeScript", "PostgreSQL"],
    postedAt: now - 5 * day,
    applyUrl: "https://startup.id/careers",
    companyLogo: "🚀",
  },
  {
    title: "Machine Learning Engineer",
    company: "Bukalapak",
    location: "Jakarta",
    workMode: "hybrid",
    employmentType: "full-time",
    seniority: "senior",
    salaryMin: 40_000_000,
    salaryMax: 70_000_000,
    currency: "IDR",
    description:
      "Bangun sistem rekomendasi produk + anti-fraud menggunakan deep learning. Latar belakang riset atau industri besar sangat dihargai.",
    requiredSkills: ["Python", "PyTorch", "MLOps", "SQL"],
    postedAt: now - 6 * day,
    applyUrl: "https://bukalapak.com/careers",
    companyLogo: "📦",
  },
  {
    title: "DevOps Engineer",
    company: "Blibli",
    location: "Tangerang",
    workMode: "onsite",
    employmentType: "full-time",
    seniority: "mid-level",
    salaryMin: 20_000_000,
    salaryMax: 35_000_000,
    currency: "IDR",
    description:
      "Kelola infrastruktur cloud untuk platform e-commerce. CI/CD, observability, security hardening.",
    requiredSkills: ["Kubernetes", "Terraform", "AWS", "Linux"],
    postedAt: now - 7 * day,
    applyUrl: "https://blibli.com/careers",
    companyLogo: "🏷️",
  },
  {
    title: "Mobile Engineer (Android)",
    company: "DANA",
    location: "Jakarta",
    workMode: "hybrid",
    employmentType: "full-time",
    seniority: "mid-level",
    salaryMin: 22_000_000,
    salaryMax: 38_000_000,
    currency: "IDR",
    description:
      "Kembangkan aplikasi dompet digital untuk jutaan pengguna. Kotlin, Jetpack Compose, performance matters.",
    requiredSkills: ["Kotlin", "Android", "Jetpack Compose", "Coroutines"],
    postedAt: now - 9 * day,
    applyUrl: "https://dana.id/careers",
    companyLogo: "💳",
  },
];
