import { promises as fs } from "fs";
import path from "path";
import { NextResponse } from "next/server";

/**
 * Build-ID echo for stale-bundle detection. Returns the live build's
 * ID by reading `.next/BUILD_ID` (written by `next build`, bundled
 * into the standalone output). The file path persists across deploys
 * so module-level caching is safe — a new container = new file.
 *
 * Why disk and not `process.env.NEXT_PUBLIC_BUILD_ID`: the `env` field
 * in `next.config.ts` injects values into the CLIENT bundle at build
 * time, but does NOT propagate to the SERVER's runtime `process.env`.
 * In a Docker/standalone container the server-side env is just whatever
 * the host injects, so reading `process.env.NEXT_PUBLIC_BUILD_ID` in a
 * route handler returns undefined unless the host explicitly sets it.
 *
 * Reading the file gives us the canonical build ID generated by
 * `generateBuildId()` for this exact deploy.
 *
 * `force-dynamic` so the response is never edge-cached — would defeat
 * the entire detection mechanism.
 */
export const dynamic = "force-dynamic";
export const revalidate = 0;

let cached: string | null = null;

async function readBuildId(): Promise<string> {
  if (cached) return cached;

  // Try the canonical Next.js build-id file. In standalone output the
  // working directory is `.next/standalone/` so `.next/BUILD_ID` is the
  // relative path. In a non-standalone dev/build it's `.next/BUILD_ID`
  // from project root — same relative path. process.cwd() handles both.
  const candidates = [
    path.join(process.cwd(), ".next", "BUILD_ID"),
    // Fallback for monorepo / unusual cwd layouts.
    path.join(process.cwd(), "..", ".next", "BUILD_ID"),
  ];

  for (const p of candidates) {
    try {
      const content = (await fs.readFile(p, "utf-8")).trim();
      if (content) {
        cached = content;
        return cached;
      }
    } catch {
      // Try next candidate.
    }
  }

  // Last-ditch: build-time env (works in dev where Next replaces it).
  cached = process.env.NEXT_PUBLIC_BUILD_ID || "unknown";
  return cached;
}

export async function GET() {
  const buildId = await readBuildId();
  return NextResponse.json(
    { buildId },
    {
      headers: {
        "Cache-Control": "no-store, max-age=0",
        "CDN-Cache-Control": "no-store",
      },
    },
  );
}
