// Auto-populated by the background agent. Placeholder until agent completes.
// Admin can load these via the "Muat Default" button in TemplatePanel.

interface TemplateResource {
  id: string;
  title: string;
  type: string;
  url: string;
  free: boolean;
}

interface TemplateNode {
  id: string;
  title: string;
  description: string;
  difficulty: string;
  estimatedHours: number;
  prerequisites: string[];
  parentId?: string;
  category?: string;
  resources: TemplateResource[];
}

export interface RoadmapTemplateData {
  title: string;
  slug: string;
  domain: string;
  icon: string;
  color: string;
  description: string;
  tags: string[];
  order: number;
  nodes: TemplateNode[];
  isPublic: boolean;
  isSystem: boolean;
}

export const defaultRoadmapTemplates: RoadmapTemplateData[] = [
  {
    title: "Frontend Developer",
    slug: "frontend",
    domain: "tech",
    icon: "Layout",
    color: "bg-blue-500",
    description: "Jalur belajar pengembang antarmuka web modern",
    tags: ["html", "css", "javascript", "react", "nextjs"],
    order: 1,
    isPublic: true,
    isSystem: true,
    nodes: [
      {
        id: "fe-1",
        title: "HTML & CSS Dasar",
        description: "Struktur dokumen web dan styling fundamental",
        difficulty: "beginner",
        estimatedHours: 20,
        prerequisites: [],
        resources: [
          { id: "fe-r1", title: "Belajar HTML Dasar - Petani Kode", type: "video", url: "https://www.youtube.com/c/PetaniKode", free: true },
          { id: "fe-r2", title: "Web Programming UNPAS - HTML5", type: "video", url: "https://www.youtube.com/c/WebProgrammingUNPAS", free: true },
          { id: "fe-r3", title: "MDN Web Docs - HTML", type: "documentation", url: "https://developer.mozilla.org/en-US/docs/Web/HTML", free: true },
        ],
      },
      {
        id: "fe-2",
        title: "CSS Intermediate & Responsive",
        description: "Flexbox, Grid, media queries, dan desain responsif",
        difficulty: "beginner",
        estimatedHours: 25,
        prerequisites: ["fe-1"],
        resources: [
          { id: "fe-r4", title: "CSS Flexbox - Kelas Terbuka", type: "video", url: "https://www.youtube.com/c/KelasTerbuka", free: true },
          { id: "fe-r5", title: "MDN Web Docs - CSS", type: "documentation", url: "https://developer.mozilla.org/en-US/docs/Web/CSS", free: true },
        ],
      },
      {
        id: "fe-3",
        title: "JavaScript Fundamental",
        description: "Bahasa pemrograman web: variabel, fungsi, DOM, event",
        difficulty: "beginner",
        estimatedHours: 40,
        prerequisites: ["fe-1"],
        resources: [
          { id: "fe-r6", title: "JavaScript - Web Programming UNPAS", type: "video", url: "https://www.youtube.com/c/WebProgrammingUNPAS", free: true },
          { id: "fe-r7", title: "JavaScript.info (Terjemahan)", type: "article", url: "https://javascript.info", free: true },
          { id: "fe-r8", title: "Dicoding - Belajar Dasar Pemrograman JavaScript", type: "course", url: "https://www.dicoding.com/academies/256", free: false },
        ],
      },
      {
        id: "fe-4",
        title: "Git & Version Control",
        description: "Mengelola kode dengan Git dan GitHub",
        difficulty: "beginner",
        estimatedHours: 10,
        prerequisites: [],
        resources: [
          { id: "fe-r9", title: "Git Tutorial - Petani Kode", type: "video", url: "https://www.youtube.com/c/PetaniKode", free: true },
          { id: "fe-r10", title: "Pro Git Book (Gratis)", type: "book", url: "https://git-scm.com/book/en/v2", free: true },
        ],
      },
      {
        id: "fe-5",
        title: "React.js",
        description: "Library UI dari Meta: komponen, state, props, hooks",
        difficulty: "intermediate",
        estimatedHours: 50,
        prerequisites: ["fe-3"],
        resources: [
          { id: "fe-r11", title: "React - Dokumentasi Resmi", type: "documentation", url: "https://react.dev", free: true },
          { id: "fe-r12", title: "Dicoding - Belajar Membuat Aplikasi Web dengan React", type: "course", url: "https://www.dicoding.com/academies/403", free: false },
          { id: "fe-r13", title: "React Tutorial - Sekolah Koding", type: "video", url: "https://www.youtube.com/@SekolahKoding", free: true },
        ],
      },
      {
        id: "fe-6",
        title: "TypeScript",
        description: "JavaScript dengan type system untuk kode yang lebih aman",
        difficulty: "intermediate",
        estimatedHours: 25,
        prerequisites: ["fe-3"],
        resources: [
          { id: "fe-r14", title: "TypeScript Handbook", type: "documentation", url: "https://www.typescriptlang.org/docs", free: true },
          { id: "fe-r15", title: "TypeScript - Programmer Zaman Now", type: "video", url: "https://www.youtube.com/@ProgrammerZamanNow", free: true },
        ],
      },
      {
        id: "fe-7",
        title: "State Management",
        description: "Zustand, Redux Toolkit, atau Context API untuk state global",
        difficulty: "intermediate",
        estimatedHours: 20,
        prerequisites: ["fe-5"],
        resources: [
          { id: "fe-r16", title: "Zustand Documentation", type: "documentation", url: "https://zustand-demo.pmnd.rs", free: true },
          { id: "fe-r17", title: "Redux Toolkit - Official Tutorial", type: "article", url: "https://redux-toolkit.js.org/tutorials/overview", free: true },
        ],
      },
      {
        id: "fe-8",
        title: "Next.js",
        description: "Framework React dengan SSR, SSG, App Router, dan API Routes",
        difficulty: "advanced",
        estimatedHours: 40,
        prerequisites: ["fe-5", "fe-6"],
        resources: [
          { id: "fe-r18", title: "Next.js - Dokumentasi Resmi", type: "documentation", url: "https://nextjs.org/docs", free: true },
          { id: "fe-r19", title: "Dicoding - Belajar Pengembangan Web Intermediet", type: "course", url: "https://www.dicoding.com/academies/276", free: false },
        ],
      },
      {
        id: "fe-9",
        title: "Testing Frontend",
        description: "Vitest, Jest, React Testing Library untuk unit dan integrasi test",
        difficulty: "advanced",
        estimatedHours: 20,
        prerequisites: ["fe-5"],
        resources: [
          { id: "fe-r20", title: "Vitest Documentation", type: "documentation", url: "https://vitest.dev", free: true },
          { id: "fe-r21", title: "React Testing Library", type: "documentation", url: "https://testing-library.com/react", free: true },
        ],
      },
      {
        id: "fe-10",
        title: "Deploy & Performa",
        description: "Lighthouse, Core Web Vitals, optimasi bundle, dan deployment",
        difficulty: "advanced",
        estimatedHours: 15,
        prerequisites: ["fe-8"],
        resources: [
          { id: "fe-r22", title: "Web.dev - Core Web Vitals", type: "article", url: "https://web.dev/vitals", free: true },
          { id: "fe-r23", title: "Dicoding - Belajar Fundamental Front-End Web", type: "course", url: "https://www.dicoding.com/academies/163", free: false },
        ],
      },
    ],
  },
  {
    title: "Backend Developer",
    slug: "backend",
    domain: "tech",
    icon: "Server",
    color: "bg-green-500",
    description: "Jalur belajar pengembang server, API, dan database",
    tags: ["nodejs", "express", "database", "api", "sql"],
    order: 2,
    isPublic: true,
    isSystem: true,
    nodes: [
      {
        id: "be-1",
        title: "Fundamental Pemrograman",
        description: "Logika pemrograman dasar: variabel, loop, fungsi, OOP",
        difficulty: "beginner",
        estimatedHours: 30,
        prerequisites: [],
        resources: [
          { id: "be-r1", title: "Dicoding - Belajar Dasar Pemrograman Web", type: "course", url: "https://www.dicoding.com/academies/174", free: false },
          { id: "be-r2", title: "Programmer Zaman Now - JavaScript OOP", type: "video", url: "https://www.youtube.com/@ProgrammerZamanNow", free: true },
        ],
      },
      {
        id: "be-2",
        title: "Node.js Dasar",
        description: "Runtime JS untuk server: modul, file system, HTTP native",
        difficulty: "beginner",
        estimatedHours: 25,
        prerequisites: ["be-1"],
        resources: [
          { id: "be-r3", title: "Node.js Documentation", type: "documentation", url: "https://nodejs.org/docs", free: true },
          { id: "be-r4", title: "Dicoding - Belajar Membuat Aplikasi Back-End", type: "course", url: "https://www.dicoding.com/academies/271", free: false },
        ],
      },
      {
        id: "be-3",
        title: "Express.js & REST API",
        description: "Framework minimalis untuk membangun REST API",
        difficulty: "intermediate",
        estimatedHours: 30,
        prerequisites: ["be-2"],
        resources: [
          { id: "be-r5", title: "Express.js Documentation", type: "documentation", url: "https://expressjs.com", free: true },
          { id: "be-r6", title: "REST API Tutorial Indonesia - Sekolah Koding", type: "video", url: "https://www.youtube.com/@SekolahKoding", free: true },
        ],
      },
      {
        id: "be-4",
        title: "SQL & Database Relasional",
        description: "MySQL/PostgreSQL: query, join, index, normalisasi",
        difficulty: "intermediate",
        estimatedHours: 35,
        prerequisites: ["be-2"],
        resources: [
          { id: "be-r7", title: "SQL Tutorial - W3Schools", type: "article", url: "https://www.w3schools.com/sql", free: true },
          { id: "be-r8", title: "Dicoding - Belajar Dasar SQL", type: "course", url: "https://www.dicoding.com/academies/480", free: false },
        ],
      },
      {
        id: "be-5",
        title: "Database NoSQL",
        description: "MongoDB: document model, CRUD, aggregation pipeline",
        difficulty: "intermediate",
        estimatedHours: 25,
        prerequisites: ["be-2"],
        resources: [
          { id: "be-r9", title: "MongoDB University - Free Courses", type: "course", url: "https://university.mongodb.com", free: true },
          { id: "be-r10", title: "MongoDB Documentation", type: "documentation", url: "https://docs.mongodb.com", free: true },
        ],
      },
      {
        id: "be-6",
        title: "Autentikasi & Keamanan",
        description: "JWT, session, hashing password, OWASP Top 10",
        difficulty: "intermediate",
        estimatedHours: 20,
        prerequisites: ["be-3"],
        resources: [
          { id: "be-r11", title: "OWASP Top 10", type: "article", url: "https://owasp.org/www-project-top-ten", free: true },
          { id: "be-r12", title: "JWT.io Introduction", type: "article", url: "https://jwt.io/introduction", free: true },
        ],
      },
      {
        id: "be-7",
        title: "Testing Backend",
        description: "Unit test, integration test dengan Jest/Supertest",
        difficulty: "advanced",
        estimatedHours: 20,
        prerequisites: ["be-3"],
        resources: [
          { id: "be-r13", title: "Jest Documentation", type: "documentation", url: "https://jestjs.io/docs/getting-started", free: true },
        ],
      },
      {
        id: "be-8",
        title: "Docker & Deployment",
        description: "Containerize aplikasi, deploy ke VPS dengan Docker Compose",
        difficulty: "advanced",
        estimatedHours: 30,
        prerequisites: ["be-3"],
        resources: [
          { id: "be-r14", title: "Docker untuk Pemula - Indonesia Belajar", type: "video", url: "https://www.youtube.com/@IndonesiaBelajar", free: true },
          { id: "be-r15", title: "Dicoding - Belajar Membangun Arsitektur Microservices", type: "course", url: "https://www.dicoding.com/academies/433", free: false },
        ],
      },
    ],
  },
  {
    title: "Digital Marketing",
    slug: "digital-marketing",
    domain: "business",
    icon: "TrendingUp",
    color: "bg-red-500",
    description: "Jalur karir pemasaran digital, SEO, dan media sosial",
    tags: ["seo", "social-media", "google-ads", "content"],
    order: 11,
    isPublic: true,
    isSystem: true,
    nodes: [
      {
        id: "dm-1",
        title: "Fondasi Digital Marketing",
        description: "Ekosistem pemasaran digital, funnel, dan KPI",
        difficulty: "beginner",
        estimatedHours: 15,
        prerequisites: [],
        resources: [
          { id: "dm-r1", title: "Google Digital Garage - Fundamental Digital Marketing", type: "course", url: "https://learndigital.withgoogle.com", free: true },
          { id: "dm-r2", title: "Skill Academy - Digital Marketing Fundamental", type: "course", url: "https://skillacademy.id", free: false },
        ],
      },
      {
        id: "dm-2",
        title: "SEO (Search Engine Optimization)",
        description: "On-page, off-page, keyword research, Google Search Console",
        difficulty: "intermediate",
        estimatedHours: 30,
        prerequisites: ["dm-1"],
        resources: [
          { id: "dm-r3", title: "Google Search Central Documentation", type: "documentation", url: "https://developers.google.com/search/docs", free: true },
          { id: "dm-r4", title: "Ahrefs Blog - SEO Guide", type: "article", url: "https://ahrefs.com/blog/learn-seo", free: true },
          { id: "dm-r5", title: "Skill Academy - SEO for Business", type: "course", url: "https://skillacademy.id", free: false },
        ],
      },
      {
        id: "dm-3",
        title: "Google Ads (SEM)",
        description: "Iklan berbayar: search ads, display ads, remarketing",
        difficulty: "intermediate",
        estimatedHours: 25,
        prerequisites: ["dm-1"],
        resources: [
          { id: "dm-r6", title: "Google Skillshop - Google Ads Certification", type: "course", url: "https://skillshop.withgoogle.com", free: true },
          { id: "dm-r7", title: "Skill Academy - Google Ads", type: "course", url: "https://skillacademy.id", free: false },
        ],
      },
      {
        id: "dm-4",
        title: "Social Media Marketing",
        description: "Strategi konten Instagram, TikTok, LinkedIn, dan Facebook",
        difficulty: "beginner",
        estimatedHours: 20,
        prerequisites: ["dm-1"],
        resources: [
          { id: "dm-r8", title: "Meta Blueprint - Facebook & Instagram", type: "course", url: "https://www.facebookblueprint.com", free: true },
          { id: "dm-r9", title: "Skill Academy - Social Media Marketing", type: "course", url: "https://skillacademy.id", free: false },
        ],
      },
      {
        id: "dm-5",
        title: "Content Marketing",
        description: "Strategi konten, content calendar, dan storytelling brand",
        difficulty: "intermediate",
        estimatedHours: 20,
        prerequisites: ["dm-4"],
        resources: [
          { id: "dm-r10", title: "HubSpot Academy - Content Marketing", type: "course", url: "https://academy.hubspot.com", free: true },
        ],
      },
      {
        id: "dm-6",
        title: "Email Marketing",
        description: "Kampanye email, segmentasi, automasi, dan A/B testing",
        difficulty: "intermediate",
        estimatedHours: 15,
        prerequisites: ["dm-1"],
        resources: [
          { id: "dm-r11", title: "Mailchimp Academy", type: "course", url: "https://mailchimp.com/resources/mailchimp-101", free: true },
        ],
      },
      {
        id: "dm-7",
        title: "Analytics & Data",
        description: "Google Analytics 4, interpretasi data, dan laporan performa",
        difficulty: "intermediate",
        estimatedHours: 20,
        prerequisites: ["dm-1"],
        resources: [
          { id: "dm-r12", title: "Google Analytics Academy", type: "course", url: "https://analytics.google.com/analytics/academy", free: true },
          { id: "dm-r13", title: "Skill Academy - Data Analytics for Marketing", type: "course", url: "https://skillacademy.id", free: false },
        ],
      },
      {
        id: "dm-8",
        title: "Strategi & Perencanaan Kampanye",
        description: "Menyusun strategi digital marketing end-to-end dan ROI",
        difficulty: "advanced",
        estimatedHours: 20,
        prerequisites: ["dm-2", "dm-3", "dm-7"],
        resources: [
          { id: "dm-r14", title: "HubSpot Academy - Digital Marketing Certification", type: "course", url: "https://academy.hubspot.com", free: true },
        ],
      },
    ],
  },
  {
    title: "Guru Sekolah (SD-SMA)",
    slug: "teacher-k12",
    domain: "education",
    icon: "GraduationCap",
    color: "bg-green-600",
    description: "Kompetensi profesional guru dari pedagogik hingga sertifikasi",
    tags: ["kurikulum-merdeka", "pedagogik", "asesmen", "ptkp"],
    order: 31,
    isPublic: true,
    isSystem: true,
    nodes: [
      {
        id: "guru-1",
        title: "Pedagogik & Teori Belajar",
        description: "Fondasi ilmu mendidik: teori konstruktivisme, pembelajaran aktif",
        difficulty: "beginner",
        estimatedHours: 20,
        prerequisites: [],
        resources: [
          { id: "guru-r1", title: "Ruangguru - Pelatihan Guru Merdeka Belajar", type: "course", url: "https://ruangguru.com", free: false },
          { id: "guru-r2", title: "Kemendikbud - Platform Merdeka Mengajar", type: "course", url: "https://guru.kemdikbud.go.id", free: true },
        ],
      },
      {
        id: "guru-2",
        title: "Kurikulum Merdeka",
        description: "Memahami struktur, capaian pembelajaran, dan implementasi Kurmer",
        difficulty: "beginner",
        estimatedHours: 25,
        prerequisites: ["guru-1"],
        resources: [
          { id: "guru-r3", title: "Platform Merdeka Mengajar - Materi Kurikulum", type: "course", url: "https://guru.kemdikbud.go.id", free: true },
          { id: "guru-r4", title: "Podcast Guru Inspiratif - Spotify", type: "other", url: "https://open.spotify.com", free: true },
        ],
      },
      {
        id: "guru-3",
        title: "Penyusunan Modul Ajar & ATP",
        description: "Membuat Alur Tujuan Pembelajaran dan Modul Ajar yang efektif",
        difficulty: "intermediate",
        estimatedHours: 30,
        prerequisites: ["guru-2"],
        resources: [
          { id: "guru-r5", title: "Kemendikbud - Contoh Modul Ajar", type: "documentation", url: "https://guru.kemdikbud.go.id/kurikulum/referensi-penerapan/materi-pelajaran", free: true },
        ],
      },
      {
        id: "guru-4",
        title: "Manajemen Kelas",
        description: "Teknik pengelolaan kelas aktif, disiplin positif, dan iklim belajar",
        difficulty: "beginner",
        estimatedHours: 15,
        prerequisites: ["guru-1"],
        resources: [
          { id: "guru-r6", title: "Ruangguru - Manajemen Kelas Efektif", type: "course", url: "https://ruangguru.com", free: false },
        ],
      },
      {
        id: "guru-5",
        title: "Asesmen & Evaluasi Pembelajaran",
        description: "Asesmen diagnostik, formatif, sumatif, dan pelaporan berbasis data",
        difficulty: "intermediate",
        estimatedHours: 25,
        prerequisites: ["guru-3"],
        resources: [
          { id: "guru-r7", title: "Platform Merdeka Mengajar - Asesmen Murid", type: "course", url: "https://guru.kemdikbud.go.id", free: true },
        ],
      },
      {
        id: "guru-6",
        title: "Literasi Digital & Teknologi Pembelajaran",
        description: "Menggunakan Canva, Quizizz, Google Workspace, dan platform edu-tech",
        difficulty: "intermediate",
        estimatedHours: 20,
        prerequisites: ["guru-1"],
        resources: [
          { id: "guru-r8", title: "Google for Education - Certified Educator", type: "course", url: "https://edu.google.com/intl/ALL_id/for-educators/certification", free: true },
          { id: "guru-r9", title: "Canva for Education (Gratis)", type: "course", url: "https://www.canva.com/id_id/pendidikan", free: true },
        ],
      },
      {
        id: "guru-7",
        title: "Projek Penguatan Profil Pelajar Pancasila (P5)",
        description: "Merancang dan memfasilitasi proyek lintas mapel berbasis P5",
        difficulty: "intermediate",
        estimatedHours: 20,
        prerequisites: ["guru-3"],
        resources: [
          { id: "guru-r10", title: "Kemendikbud - Panduan P5", type: "documentation", url: "https://guru.kemdikbud.go.id", free: true },
        ],
      },
      {
        id: "guru-8",
        title: "Administrasi Sekolah",
        description: "Rapor, data siswa, e-KTSP, dan sistem administrasi sekolah",
        difficulty: "beginner",
        estimatedHours: 15,
        prerequisites: [],
        resources: [
          { id: "guru-r11", title: "Dapodik - Panduan Input Data", type: "documentation", url: "https://dapo.kemdikbud.go.id", free: true },
        ],
      },
      {
        id: "guru-9",
        title: "Pengembangan Diri & PTKP",
        description: "PKG, PTKP, portofolio guru, dan pengembangan keprofesionalan berkelanjutan",
        difficulty: "advanced",
        estimatedHours: 30,
        prerequisites: ["guru-5", "guru-6"],
        resources: [
          { id: "guru-r12", title: "Kemendikbud - Guru Penggerak", type: "course", url: "https://sekolah.penggerak.kemdikbud.go.id", free: true },
          { id: "guru-r13", title: "Ruangguru - Persiapan PPG", type: "course", url: "https://ruangguru.com", free: false },
        ],
      },
    ],
  },
  {
    title: "Akuntansi & Keuangan",
    slug: "accounting",
    domain: "finance",
    icon: "Calculator",
    color: "bg-emerald-600",
    description: "Kompetensi akuntan dari pembukuan hingga analisis laporan keuangan",
    tags: ["akuntansi", "perpajakan", "excel", "laporan-keuangan"],
    order: 51,
    isPublic: true,
    isSystem: true,
    nodes: [
      {
        id: "akun-1",
        title: "Akuntansi Dasar",
        description: "Persamaan akuntansi, jurnal, buku besar, neraca saldo",
        difficulty: "beginner",
        estimatedHours: 30,
        prerequisites: [],
        resources: [
          { id: "akun-r1", title: "Skill Academy - Akuntansi Dasar", type: "course", url: "https://skillacademy.id", free: false },
          { id: "akun-r2", title: "YouTube - Akuntansi.id Channel", type: "video", url: "https://www.youtube.com/@akuntansiid", free: true },
        ],
      },
      {
        id: "akun-2",
        title: "Microsoft Excel untuk Keuangan",
        description: "Fungsi keuangan Excel, pivot table, dan dashboard laporan",
        difficulty: "beginner",
        estimatedHours: 20,
        prerequisites: [],
        resources: [
          { id: "akun-r3", title: "Skill Academy - Microsoft Excel", type: "course", url: "https://skillacademy.id", free: false },
          { id: "akun-r4", title: "Exceljet - Excel Formulas", type: "article", url: "https://exceljet.net/formulas", free: true },
        ],
      },
      {
        id: "akun-3",
        title: "Akuntansi Keuangan Menengah",
        description: "PSAK, laporan keuangan komersial, depresiasi, dan persediaan",
        difficulty: "intermediate",
        estimatedHours: 40,
        prerequisites: ["akun-1"],
        resources: [
          { id: "akun-r5", title: "IAI - Standar Akuntansi Keuangan", type: "documentation", url: "https://iaiglobal.or.id", free: false },
        ],
      },
      {
        id: "akun-4",
        title: "Perpajakan Indonesia",
        description: "PPh Pasal 21, PPh Badan, PPN, e-Filing DJP Online",
        difficulty: "intermediate",
        estimatedHours: 35,
        prerequisites: ["akun-1"],
        resources: [
          { id: "akun-r6", title: "DJP Online - Tutorial e-Filing", type: "documentation", url: "https://djponline.pajak.go.id", free: true },
          { id: "akun-r7", title: "Skill Academy - Perpajakan Dasar", type: "course", url: "https://skillacademy.id", free: false },
        ],
      },
      {
        id: "akun-5",
        title: "Software Akuntansi",
        description: "Mengoperasikan ACCURATE, Jurnal.id, atau Odoo untuk UMKM",
        difficulty: "intermediate",
        estimatedHours: 20,
        prerequisites: ["akun-1"],
        resources: [
          { id: "akun-r8", title: "Jurnal.id - Tutorial Lengkap", type: "video", url: "https://www.jurnal.id/id/help", free: true },
          { id: "akun-r9", title: "ACCURATE Online Help Center", type: "documentation", url: "https://help.accurate.id", free: true },
        ],
      },
      {
        id: "akun-6",
        title: "Analisis Laporan Keuangan",
        description: "Rasio keuangan, analisis tren, dan interpretasi kinerja perusahaan",
        difficulty: "advanced",
        estimatedHours: 30,
        prerequisites: ["akun-3"],
        resources: [
          { id: "akun-r10", title: "Investopedia - Financial Analysis", type: "article", url: "https://www.investopedia.com/financial-analysis-4689801", free: true },
        ],
      },
      {
        id: "akun-7",
        title: "Audit Dasar",
        description: "Prosedur audit, kertas kerja, dan standar audit (ISA/SPAP)",
        difficulty: "advanced",
        estimatedHours: 35,
        prerequisites: ["akun-3", "akun-4"],
        resources: [
          { id: "akun-r11", title: "IAPI - Standar Profesi Akuntan Publik", type: "documentation", url: "https://iapi.or.id", free: false },
        ],
      },
      {
        id: "akun-8",
        title: "Sertifikasi Profesi",
        description: "Persiapan ujian CAP, CPAI, atau Brevet Pajak",
        difficulty: "advanced",
        estimatedHours: 60,
        prerequisites: ["akun-3", "akun-4", "akun-6"],
        resources: [
          { id: "akun-r12", title: "IAI - Chartered Accountant Indonesia", type: "course", url: "https://iaiglobal.or.id", free: false },
          { id: "akun-r13", title: "Skill Academy - Brevet Pajak A & B", type: "course", url: "https://skillacademy.id", free: false },
        ],
      },
    ],
  },
  {
    title: "Human Resources",
    slug: "hr-generalist",
    domain: "hr",
    icon: "Users",
    color: "bg-indigo-500",
    description: "Kompetensi HR generalis dari rekrutmen hingga pengembangan SDM",
    tags: ["rekrutmen", "payroll", "bpjs", "hubungan-industrial"],
    order: 61,
    isPublic: true,
    isSystem: true,
    nodes: [
      {
        id: "hr-1",
        title: "Fondasi HR Management",
        description: "Fungsi HR: rekrutmen, kompensasi, pelatihan, dan hubungan industrial",
        difficulty: "beginner",
        estimatedHours: 20,
        prerequisites: [],
        resources: [
          { id: "hr-r1", title: "Skill Academy - Human Resource Management", type: "course", url: "https://skillacademy.id", free: false },
          { id: "hr-r2", title: "SHRM - HR Topics", type: "article", url: "https://www.shrm.org/topics-tools", free: true },
        ],
      },
      {
        id: "hr-2",
        title: "Rekrutmen & Seleksi",
        description: "Sourcing, screening CV, wawancara terstruktur, dan assessment",
        difficulty: "intermediate",
        estimatedHours: 25,
        prerequisites: ["hr-1"],
        resources: [
          { id: "hr-r3", title: "LinkedIn Talent Solutions - Panduan Rekrutmen", type: "article", url: "https://business.linkedin.com/talent-solutions", free: true },
          { id: "hr-r4", title: "Skill Academy - Talent Acquisition", type: "course", url: "https://skillacademy.id", free: false },
        ],
      },
      {
        id: "hr-3",
        title: "Kompensasi, Benefit & Payroll",
        description: "Struktur gaji, PPh 21, BPJS Ketenagakerjaan, dan BPJS Kesehatan",
        difficulty: "intermediate",
        estimatedHours: 30,
        prerequisites: ["hr-1"],
        resources: [
          { id: "hr-r5", title: "BPJS Ketenagakerjaan - Panduan Pemberi Kerja", type: "documentation", url: "https://www.bpjsketenagakerjaan.go.id", free: true },
          { id: "hr-r6", title: "DJP Online - Panduan PPh 21", type: "documentation", url: "https://djponline.pajak.go.id", free: true },
        ],
      },
      {
        id: "hr-4",
        title: "Hukum Ketenagakerjaan",
        description: "UU Cipta Kerja, UU No.13/2003, PKB, dan penyelesaian PHK",
        difficulty: "intermediate",
        estimatedHours: 25,
        prerequisites: ["hr-1"],
        resources: [
          { id: "hr-r7", title: "Hukumonline - Ketenagakerjaan", type: "article", url: "https://www.hukumonline.com/hukum/ketenagakerjaan", free: true },
        ],
      },
      {
        id: "hr-5",
        title: "Pelatihan & Pengembangan SDM",
        description: "Training needs analysis, desain program pelatihan, dan evaluasi",
        difficulty: "intermediate",
        estimatedHours: 20,
        prerequisites: ["hr-1"],
        resources: [
          { id: "hr-r8", title: "Skill Academy - Learning & Development", type: "course", url: "https://skillacademy.id", free: false },
        ],
      },
      {
        id: "hr-6",
        title: "Performance Management",
        description: "KPI, OKR, penilaian kinerja, dan feedback berkelanjutan",
        difficulty: "advanced",
        estimatedHours: 20,
        prerequisites: ["hr-2", "hr-5"],
        resources: [
          { id: "hr-r9", title: "Re:Work by Google - OKR Guide", type: "article", url: "https://rework.withgoogle.com", free: true },
        ],
      },
      {
        id: "hr-7",
        title: "HR Information System (HRIS)",
        description: "Mengoperasikan software HRIS: Talenta, Mekari Flex, atau BambooHR",
        difficulty: "intermediate",
        estimatedHours: 15,
        prerequisites: ["hr-1"],
        resources: [
          { id: "hr-r10", title: "Mekari Talenta - Tutorial", type: "documentation", url: "https://talenta.co/blog", free: true },
        ],
      },
      {
        id: "hr-8",
        title: "Sertifikasi HR Profesional",
        description: "Persiapan sertifikasi BNSP bidang MSDM atau HRCI PHR",
        difficulty: "advanced",
        estimatedHours: 50,
        prerequisites: ["hr-2", "hr-3", "hr-4", "hr-6"],
        resources: [
          { id: "hr-r11", title: "BNSP - Skema Sertifikasi MSDM", type: "documentation", url: "https://bnsp.go.id", free: true },
        ],
      },
    ],
  },
  {
    title: "UI/UX Designer",
    slug: "ui-ux-design",
    domain: "creative",
    icon: "Palette",
    color: "bg-pink-500",
    description: "Jalur desainer produk digital dari riset hingga prototype",
    tags: ["figma", "user-research", "prototyping", "design-system"],
    order: 21,
    isPublic: true,
    isSystem: true,
    nodes: [
      {
        id: "ux-1",
        title: "Prinsip Desain Visual",
        description: "Tipografi, warna, whitespace, kontras, dan hierarki visual",
        difficulty: "beginner",
        estimatedHours: 20,
        prerequisites: [],
        resources: [
          { id: "ux-r1", title: "Refactoring UI - Book", type: "book", url: "https://www.refactoringui.com", free: false },
          { id: "ux-r2", title: "Material Design Guidelines", type: "documentation", url: "https://m3.material.io", free: true },
        ],
      },
      {
        id: "ux-2",
        title: "Figma Mastery",
        description: "Auto-layout, komponen, variabel, dan design system di Figma",
        difficulty: "beginner",
        estimatedHours: 30,
        prerequisites: [],
        resources: [
          { id: "ux-r3", title: "Figma - Learn Design", type: "course", url: "https://www.figma.com/resources/learn-design", free: true },
          { id: "ux-r4", title: "Skill Academy - UI Design dengan Figma", type: "course", url: "https://skillacademy.id", free: false },
        ],
      },
      {
        id: "ux-3",
        title: "User Research",
        description: "User interview, survei, usability testing, dan affinity mapping",
        difficulty: "intermediate",
        estimatedHours: 25,
        prerequisites: ["ux-1"],
        resources: [
          { id: "ux-r5", title: "Nielsen Norman Group - UX Research", type: "article", url: "https://www.nngroup.com/articles/which-ux-research-methods", free: true },
          { id: "ux-r6", title: "Interaction Design Foundation - User Research", type: "course", url: "https://www.interaction-design.org", free: false },
        ],
      },
      {
        id: "ux-4",
        title: "Information Architecture",
        description: "Sitemap, card sorting, user flow, dan navigasi yang intuitif",
        difficulty: "intermediate",
        estimatedHours: 15,
        prerequisites: ["ux-3"],
        resources: [
          { id: "ux-r7", title: "IA Institute - Basics of IA", type: "article", url: "https://www.iainstitute.org", free: true },
        ],
      },
      {
        id: "ux-5",
        title: "Wireframing & Prototyping",
        description: "Low-fidelity wireframe, high-fidelity mockup, dan prototype interaktif",
        difficulty: "intermediate",
        estimatedHours: 25,
        prerequisites: ["ux-2", "ux-4"],
        resources: [
          { id: "ux-r8", title: "Figma - Prototyping Guide", type: "documentation", url: "https://help.figma.com/hc/en-us/categories/360002051613", free: true },
        ],
      },
      {
        id: "ux-6",
        title: "Design System",
        description: "Membangun komponen library, token desain, dan dokumentasi sistem",
        difficulty: "advanced",
        estimatedHours: 30,
        prerequisites: ["ux-2", "ux-5"],
        resources: [
          { id: "ux-r9", title: "Atlassian Design System", type: "documentation", url: "https://atlassian.design", free: true },
          { id: "ux-r10", title: "Zero Height - Design System Guide", type: "article", url: "https://zeroheight.com/blog/what-is-a-design-system", free: true },
        ],
      },
      {
        id: "ux-7",
        title: "Aksesibilitas (A11y)",
        description: "WCAG 2.1, contrast checker, screen reader, dan inclusive design",
        difficulty: "advanced",
        estimatedHours: 15,
        prerequisites: ["ux-5"],
        resources: [
          { id: "ux-r11", title: "WebAIM - Web Accessibility", type: "article", url: "https://webaim.org", free: true },
        ],
      },
      {
        id: "ux-8",
        title: "Portofolio & Presentasi",
        description: "Menyusun case study, UX writing, dan presentasi ke stakeholder",
        difficulty: "advanced",
        estimatedHours: 20,
        prerequisites: ["ux-5", "ux-3"],
        resources: [
          { id: "ux-r12", title: "Bestfolios - UX Portfolio Inspiration", type: "article", url: "https://www.bestfolios.com/portfolios", free: true },
        ],
      },
    ],
  },
  {
    title: "Project Manager",
    slug: "project-manager",
    domain: "business",
    icon: "Briefcase",
    color: "bg-slate-600",
    description: "Mengelola proyek dari inisiasi hingga penutupan dengan metodologi terstruktur",
    tags: ["pmp", "scrum", "agile", "jira", "manajemen-risiko"],
    order: 13,
    isPublic: true,
    isSystem: true,
    nodes: [
      {
        id: "pm-1",
        title: "Fondasi Manajemen Proyek",
        description: "5 kelompok proses, 10 area pengetahuan PMBOK, dan triple constraint",
        difficulty: "beginner",
        estimatedHours: 20,
        prerequisites: [],
        resources: [
          { id: "pm-r1", title: "PMI - Project Management Basics", type: "article", url: "https://www.pmi.org/learning/library", free: true },
          { id: "pm-r2", title: "Skill Academy - Project Management Fundamental", type: "course", url: "https://skillacademy.id", free: false },
        ],
      },
      {
        id: "pm-2",
        title: "Agile & Scrum",
        description: "Sprint, backlog, daily standup, retrospective, dan Scrum Master role",
        difficulty: "intermediate",
        estimatedHours: 25,
        prerequisites: ["pm-1"],
        resources: [
          { id: "pm-r3", title: "Scrum Guide 2020 (Bahasa Indonesia)", type: "book", url: "https://scrumguides.org/docs/scrumguide/v2020/2020-Scrum-Guide-Indonesian.pdf", free: true },
          { id: "pm-r4", title: "Scrum.org - Learning Path", type: "course", url: "https://www.scrum.org/pathway/scrum-master", free: true },
        ],
      },
      {
        id: "pm-3",
        title: "Tools: Jira, Trello & Asana",
        description: "Mengelola backlog, sprint board, dan pelaporan dengan tools populer",
        difficulty: "beginner",
        estimatedHours: 15,
        prerequisites: ["pm-1"],
        resources: [
          { id: "pm-r5", title: "Atlassian - Jira Software Tutorials", type: "course", url: "https://university.atlassian.com", free: true },
          { id: "pm-r6", title: "Asana Academy", type: "course", url: "https://academy.asana.com", free: true },
        ],
      },
      {
        id: "pm-4",
        title: "Manajemen Risiko & Stakeholder",
        description: "Identifikasi risiko, mitigasi, dan komunikasi dengan stakeholder",
        difficulty: "intermediate",
        estimatedHours: 20,
        prerequisites: ["pm-1"],
        resources: [
          { id: "pm-r7", title: "PMI - Risk Management Professional", type: "article", url: "https://www.pmi.org/certifications/risk-management-rmp", free: true },
        ],
      },
      {
        id: "pm-5",
        title: "Perencanaan & Estimasi Proyek",
        description: "WBS, Gantt chart, estimasi effort, critical path method",
        difficulty: "intermediate",
        estimatedHours: 20,
        prerequisites: ["pm-1"],
        resources: [
          { id: "pm-r8", title: "MS Project Tutorial (Gratis)", type: "video", url: "https://www.youtube.com/results?search_query=ms+project+tutorial+bahasa+indonesia", free: true },
        ],
      },
      {
        id: "pm-6",
        title: "Sertifikasi PMP / CAPM",
        description: "Persiapan ujian Project Management Professional atau CAPM",
        difficulty: "advanced",
        estimatedHours: 80,
        prerequisites: ["pm-1", "pm-2", "pm-4", "pm-5"],
        resources: [
          { id: "pm-r9", title: "PMI - PMP Certification", type: "course", url: "https://www.pmi.org/certifications/project-management-pmp", free: false },
          { id: "pm-r10", title: "Coursera - Google Project Management Certificate", type: "course", url: "https://www.coursera.org/professional-certificates/google-project-management", free: false },
        ],
      },
    ],
  },
  {
    title: "ASN / PNS",
    slug: "asn",
    domain: "government",
    icon: "Landmark",
    color: "bg-blue-700",
    description: "Kompetensi teknis dan manajerial Aparatur Sipil Negara Indonesia",
    tags: ["cpns", "pppk", "latsar", "kompetensi-asn"],
    order: 71,
    isPublic: true,
    isSystem: true,
    nodes: [
      {
        id: "asn-1",
        title: "Seleksi CPNS / PPPK",
        description: "TWK, TIU, TKP, SKD, SKB — strategi persiapan ujian seleksi ASN",
        difficulty: "beginner",
        estimatedHours: 60,
        prerequisites: [],
        resources: [
          { id: "asn-r1", title: "BKN - Informasi Seleksi ASN Resmi", type: "documentation", url: "https://bkn.go.id", free: true },
          { id: "asn-r2", title: "SSCASN - Portal Resmi Pendaftaran", type: "documentation", url: "https://sscasn.bkn.go.id", free: true },
          { id: "asn-r3", title: "Ruangguru - Persiapan CPNS", type: "course", url: "https://ruangguru.com", free: false },
        ],
      },
      {
        id: "asn-2",
        title: "Latsar CPNS (Pelatihan Dasar)",
        description: "Core values BerAKHLAK, Smart ASN, manajemen ASN, dan NKRI",
        difficulty: "beginner",
        estimatedHours: 40,
        prerequisites: ["asn-1"],
        resources: [
          { id: "asn-r4", title: "LAN - e-Learning ASN Unggul", type: "course", url: "https://asn.lan.go.id", free: true },
          { id: "asn-r5", title: "MOOC PPPK - LAN RI", type: "course", url: "https://mooc.lan.go.id", free: true },
        ],
      },
      {
        id: "asn-3",
        title: "Administrasi Pemerintahan",
        description: "Tata naskah dinas, kearsipan, e-office, dan SOP pemerintahan",
        difficulty: "intermediate",
        estimatedHours: 25,
        prerequisites: ["asn-2"],
        resources: [
          { id: "asn-r6", title: "ANRI - Panduan Kearsipan Pemerintah", type: "documentation", url: "https://anri.go.id", free: true },
        ],
      },
      {
        id: "asn-4",
        title: "E-Government & Digitalisasi",
        description: "SPBE, aplikasi pemerintah (SIASN, SIMPEGDA), dan layanan digital",
        difficulty: "intermediate",
        estimatedHours: 20,
        prerequisites: ["asn-2"],
        resources: [
          { id: "asn-r7", title: "BKN - SIASN User Manual", type: "documentation", url: "https://bkn.go.id", free: true },
          { id: "asn-r8", title: "Kominfo - Panduan SPBE", type: "documentation", url: "https://spbe.go.id", free: true },
        ],
      },
      {
        id: "asn-5",
        title: "Manajemen Kinerja ASN",
        description: "SKP, e-Kinerja BKN, penilaian prestasi kerja, dan laporan kinerja",
        difficulty: "intermediate",
        estimatedHours: 20,
        prerequisites: ["asn-2"],
        resources: [
          { id: "asn-r9", title: "BKN - e-Kinerja Manual", type: "documentation", url: "https://kinerja.bkn.go.id", free: true },
        ],
      },
      {
        id: "asn-6",
        title: "Pengembangan Kompetensi ASN",
        description: "Diklat fungsional, 20 JPL pertahun, dan jalur pengembangan karir",
        difficulty: "advanced",
        estimatedHours: 30,
        prerequisites: ["asn-3", "asn-5"],
        resources: [
          { id: "asn-r10", title: "LAN - Katalog Diklat ASN", type: "course", url: "https://asn.lan.go.id", free: true },
          { id: "asn-r11", title: "BKN - Panduan Jabatan Fungsional", type: "documentation", url: "https://bkn.go.id", free: true },
        ],
      },
    ],
  },
  {
    title: "Perawat",
    slug: "nurse",
    domain: "health",
    icon: "Stethoscope",
    color: "bg-blue-400",
    description: "Kompetensi keperawatan klinis dari dasar hingga sertifikasi profesi",
    tags: ["keperawatan", "klinik", "ppni", "ukom"],
    order: 41,
    isPublic: true,
    isSystem: true,
    nodes: [
      {
        id: "ners-1",
        title: "Dasar Keperawatan",
        description: "Konsep dasar keperawatan, etika profesi, dan komunikasi terapeutik",
        difficulty: "beginner",
        estimatedHours: 30,
        prerequisites: [],
        resources: [
          { id: "ners-r1", title: "PPNI - Standar Profesi Perawat Indonesia", type: "documentation", url: "https://www.inna-ppni.or.id", free: true },
        ],
      },
      {
        id: "ners-2",
        title: "Keperawatan Medikal Bedah",
        description: "Asuhan keperawatan pasien penyakit dalam dan bedah",
        difficulty: "intermediate",
        estimatedHours: 40,
        prerequisites: ["ners-1"],
        resources: [
          { id: "ners-r2", title: "NANDA International - Diagnosa Keperawatan", type: "book", url: "https://nanda.org", free: false },
        ],
      },
      {
        id: "ners-3",
        title: "Keselamatan Pasien & K3RS",
        description: "Patient safety, 6 sasaran keselamatan, dan standar SNARS/JCI",
        difficulty: "intermediate",
        estimatedHours: 20,
        prerequisites: ["ners-1"],
        resources: [
          { id: "ners-r3", title: "KARS - Standar Akreditasi Rumah Sakit", type: "documentation", url: "https://kars.or.id", free: false },
          { id: "ners-r4", title: "WHO - Patient Safety Curriculum", type: "course", url: "https://www.who.int/teams/integrated-health-services/patient-safety/education-and-research/medical-schools", free: true },
        ],
      },
      {
        id: "ners-4",
        title: "Dokumentasi Keperawatan",
        description: "Rekam medis elektronik, SOAP, dan sistem informasi RS",
        difficulty: "beginner",
        estimatedHours: 15,
        prerequisites: ["ners-1"],
        resources: [
          { id: "ners-r5", title: "Permenkes 269 - Rekam Medis", type: "documentation", url: "https://peraturan.bpk.go.id", free: true },
        ],
      },
      {
        id: "ners-5",
        title: "Uji Kompetensi Ners (UKOM)",
        description: "Persiapan ujian kompetensi nasional perawat Indonesia",
        difficulty: "advanced",
        estimatedHours: 60,
        prerequisites: ["ners-2", "ners-3"],
        resources: [
          { id: "ners-r6", title: "LPUK Nakes - Uji Kompetensi Ners", type: "documentation", url: "https://lpuknakes.kemkes.go.id", free: true },
        ],
      },
      {
        id: "ners-6",
        title: "Keperawatan Gawat Darurat",
        description: "Triase, BTCLS, BLS, dan penanganan kegawatdaruratan",
        difficulty: "advanced",
        estimatedHours: 30,
        prerequisites: ["ners-2"],
        resources: [
          { id: "ners-r7", title: "BTCLS Indonesia - Basic Trauma Cardiac Life Support", type: "course", url: "https://www.pelatihankesehatan.com", free: false },
        ],
      },
    ],
  },
];
