import type { SeedCountryDocs } from "./types";

export const AE_DOCS: SeedCountryDocs = {
  country: "AE",
  countryLabel: "Uni Emirat Arab",
  flag: "🇦🇪",
  description: "Dokumen untuk UAE Employment Visa / Golden Visa / Green Visa.",
  documents: [
    {
      id: "ae-employment-visa",
      title: "Employment Entry Permit",
      description: "Diajukan sponsor (perusahaan) ke MoHRE. Setelah keluar baru bisa entry UAE.",
      category: "visa",
      required: true,
      issuingAuthority: "MoHRE",
    },
    {
      id: "ae-residence-visa",
      title: "Residence Visa (setelah masuk UAE)",
      description: "Stempel residence di paspor dalam 60 hari setelah entry. Valid 2-3 tahun.",
      category: "visa",
      required: true,
      issuingAuthority: "GDRFA",
      validityYears: 3,
    },
    {
      id: "ae-emirates-id",
      title: "Emirates ID",
      description: "ID resident UAE. Diajukan saat residence visa. Wajib untuk semua urusan.",
      category: "identity",
      required: true,
      issuingAuthority: "ICA",
    },
    {
      id: "ae-passport",
      title: "Paspor (validitas min 6 bulan)",
      description: "Paspor RI dengan halaman kosong cukup.",
      category: "travel",
      required: true,
      issuingAuthority: "Imigrasi RI",
    },
    {
      id: "ae-medical-fitness",
      title: "Medical Fitness Test",
      description: "Tes di UAE setelah entry: TB, HIV, Hepatitis. Wajib untuk residence visa.",
      category: "health",
      required: true,
    },
    {
      id: "ae-attestation-degree",
      title: "Attestasi Ijazah (MOFA UAE)",
      description: "Ijazah + apostille Kemlu RI + legalisir Kedutaan UAE + MOFA UAE setelah datang.",
      category: "education",
      required: true,
      issuingAuthority: "MOFA UAE",
    },
    {
      id: "ae-employment-contract",
      title: "Employment Contract MoHRE-registered",
      description: "Kontrak harus terdaftar MoHRE. Bonus, perks, end-of-service gratuity wajib ditulis.",
      category: "employment",
      required: true,
    },
    {
      id: "ae-resume-english",
      title: "CV (English atau Arabic)",
      description: "Format internasional. Untuk sektor Pemerintah tambahkan versi Arabic.",
      category: "career",
      required: true,
    },
    {
      id: "ae-skck-legalized",
      title: "SKCK + Attestasi Kedutaan UAE",
      description: "Untuk sebagian sektor (banking, security). SKCK + Apostille + Kedutaan UAE.",
      category: "legal",
      required: false,
      validityYears: 1,
    },
    {
      id: "ae-bank-account",
      title: "Rekening Bank UAE",
      description: "Dibuat setelah Emirates ID. Diperlukan untuk gaji + remitansi.",
      category: "financial",
      required: true,
    },
  ],
};
