import type { SeedCountryDocs } from "./types";

export const AU_DOCS: SeedCountryDocs = {
  country: "AU",
  countryLabel: "Australia",
  flag: "🇦🇺",
  description: "Dokumen untuk Skilled Worker (subclass 482 / 186 / 189), Graduate Visa (485), Working Holiday (462).",
  documents: [
    {
      id: "au-ielts-7",
      title: "IELTS 6.0+ (academic) / PTE setara",
      description: "Min IELTS 6 each band untuk visa 482; 7+ memberi lebih banyak poin SkillSelect.",
      category: "language",
      required: true,
    },
    {
      id: "au-skill-assessment",
      title: "Skills Assessment (ACS / Engineers Australia / TRA)",
      description: "Penilaian skill oleh authorised assessing body sesuai ANZSCO occupation kode.",
      category: "qualification",
      required: true,
    },
    {
      id: "au-eoi",
      title: "Expression of Interest (EOI) di SkillSelect",
      description: "Untuk visa 189 / 190 / 491. Skor min 65 poin.",
      category: "visa",
      required: false,
    },
    {
      id: "au-nomination-482",
      title: "Sponsor Nomination (visa 482)",
      description: "Sponsor harus Australian-business + occupation di STSOL/MLTSSL list.",
      category: "employment",
      required: false,
    },
    {
      id: "au-passport",
      title: "Paspor (validitas min 6 bulan)",
      description: "Paspor RI.",
      category: "travel",
      required: true,
      issuingAuthority: "Imigrasi RI",
    },
    {
      id: "au-medical-bupa",
      title: "Medical Examination (BUPA / Medibank panel)",
      description: "Health check at panel doctor in Indonesia. Untuk visa onshore subclass.",
      category: "health",
      required: true,
    },
    {
      id: "au-pcc",
      title: "Police Clearance Certificate (SKCK)",
      description: "SKCK + AFP check kalau pernah tinggal di AU 12+ bulan setelah usia 16.",
      category: "legal",
      required: true,
      validityYears: 1,
    },
    {
      id: "au-degree-translation",
      title: "Ijazah & Transkrip + Terjemahan NAATI",
      description: "Terjemahan resmi oleh NAATI-certified translator untuk visa application.",
      category: "education",
      required: true,
    },
    {
      id: "au-medicare",
      title: "Medicare (kalau visa eligible)",
      description: "Akses healthcare publik. Hanya untuk PR + subclass tertentu (482 ada Reciprocal).",
      category: "insurance",
      required: false,
    },
    {
      id: "au-tfn",
      title: "Tax File Number (TFN)",
      description: "Daftar di ATO setelah datang. Wajib untuk gaji + super.",
      category: "financial",
      required: true,
      issuingAuthority: "ATO",
    },
    {
      id: "au-resume-english",
      title: "CV (English, format Australian)",
      description: "Max 2 halaman, no foto, refs available on request, urutan waktu mundur.",
      category: "career",
      required: true,
    },
  ],
};
