import type { SeedCountryDocs } from "./types";

export const DE_DOCS: SeedCountryDocs = {
  country: "DE",
  countryLabel: "Jerman",
  flag: "🇩🇪",
  description: "Dokumen untuk Ausbildung (vocational), EU Blue Card (skilled), atau Job Seeker Visa (§ 20).",
  documents: [
    {
      id: "de-deutsch-b1",
      title: "Sertifikat Bahasa Jerman B1/B2 (Goethe / telc)",
      description: "B1 minimum untuk Ausbildung; B2+ untuk Blue Card kalau pekerjaan utama bahasa Jerman.",
      category: "language",
      required: true,
      issuingAuthority: "Goethe-Institut / telc",
    },
    {
      id: "de-ausbildungsvertrag",
      title: "Ausbildungsvertrag (kontrak vokasi)",
      description: "Kontrak dual-studies 3 tahun dari perusahaan Jerman. Untuk Ausbildung visa § 16a.",
      category: "employment",
      required: false,
    },
    {
      id: "de-blue-card-contract",
      title: "Kontrak Kerja (EU Blue Card)",
      description: "Min gaji €45.300/thn (2025) atau €41.041 untuk shortage occupations.",
      category: "employment",
      required: false,
    },
    {
      id: "de-ijazah-aab",
      title: "Pengakuan Ijazah (Anabin / ZAB)",
      description: "Cek di database Anabin atau apply Statement of Comparability ZAB. Wajib untuk Blue Card.",
      category: "education",
      required: true,
      issuingAuthority: "Zentralstelle für ausländisches Bildungswesen (ZAB)",
    },
    {
      id: "de-passport",
      title: "Paspor (validitas min 12 bulan)",
      description: "Paspor RI.",
      category: "travel",
      required: true,
      issuingAuthority: "Imigrasi RI",
    },
    {
      id: "de-visa-national",
      title: "Visa Nasional / D (Long-stay)",
      description: "Diajukan ke Kedutaan Jerman. Dokumen lengkap → 6-12 minggu proses.",
      category: "visa",
      required: true,
      issuingAuthority: "Kedutaan Jerman",
    },
    {
      id: "de-krankenversicherung",
      title: "Asuransi Kesehatan Jerman (Krankenversicherung)",
      description: "Wajib di Jerman. Pilihan: gesetzlich (TK / AOK) atau privat. Bukti coverage untuk visa.",
      category: "insurance",
      required: true,
    },
    {
      id: "de-anmeldung",
      title: "Anmeldung (registrasi alamat)",
      description: "Wajib daftar alamat di Bürgeramt dalam 14 hari sejak datang. Dasar SteuerID + bank.",
      category: "settlement",
      required: true,
      issuingAuthority: "Bürgeramt",
    },
    {
      id: "de-sperrkonto",
      title: "Sperrkonto (Blocked Account)",
      description: "€11.904 (2025) di Fintiba / Coracle untuk Job Seeker Visa / Student.",
      category: "financial",
      required: false,
    },
    {
      id: "de-resume-cv-german",
      title: "Lebenslauf (CV format Jerman)",
      description: "CV tabular, foto opsional, urut waktu mundur, tanda tangan asli di bagian bawah.",
      category: "career",
      required: true,
    },
    {
      id: "de-fuehrungszeugnis",
      title: "SKCK + Apostille (Polizeiliches Führungszeugnis equivalent)",
      description: "SKCK + apostille Kemlu RI + legalisir Kedutaan Jerman.",
      category: "legal",
      required: true,
      validityYears: 1,
    },
  ],
};
