import type { SeedCountryDocs } from "./types";

export const ID_DOCS: SeedCountryDocs = {
  country: "ID",
  countryLabel: "Indonesia",
  flag: "🇮🇩",
  description: "Dokumen wajib WNI untuk bekerja di dalam negeri + dasar untuk pengurusan dokumen luar negeri.",
  documents: [
    {
      id: "id-ktp",
      title: "Kartu Tanda Penduduk (KTP)",
      description: "Identitas resmi WNI dewasa. Diperlukan untuk hampir semua pengurusan administrasi.",
      category: "identity",
      required: true,
      issuingAuthority: "Dukcapil",
    },
    {
      id: "id-kk",
      title: "Kartu Keluarga (KK)",
      description: "Bukti susunan keluarga. Diperlukan untuk pembuatan paspor + visa.",
      category: "identity",
      required: true,
      issuingAuthority: "Dukcapil",
    },
    {
      id: "id-akta-lahir",
      title: "Akta Kelahiran",
      description: "Bukti kelahiran. Wajib untuk pengurusan dokumen internasional.",
      category: "identity",
      required: true,
      issuingAuthority: "Dukcapil",
    },
    {
      id: "id-npwp",
      title: "Nomor Pokok Wajib Pajak (NPWP)",
      description: "Nomor wajib pajak. Diperlukan untuk kontrak kerja formal + remitansi luar negeri.",
      category: "financial",
      required: true,
      issuingAuthority: "DJP Kemenkeu",
    },
    {
      id: "id-bpjs-kesehatan",
      title: "BPJS Kesehatan",
      description: "Asuransi kesehatan nasional. Wajib bagi pekerja formal.",
      category: "insurance",
      required: true,
      issuingAuthority: "BPJS Kesehatan",
    },
    {
      id: "id-bpjs-ketenagakerjaan",
      title: "BPJS Ketenagakerjaan",
      description: "Jaminan sosial pekerja. Otomatis didaftarkan oleh perusahaan.",
      category: "insurance",
      required: true,
      issuingAuthority: "BPJS Ketenagakerjaan",
    },
    {
      id: "id-paspor",
      title: "Paspor RI",
      description: "Dokumen perjalanan internasional. Pengajuan online via M-Paspor.",
      category: "travel",
      required: false,
      issuingAuthority: "Imigrasi",
      validityYears: 10,
    },
    {
      id: "id-skck",
      title: "Surat Keterangan Catatan Kepolisian (SKCK)",
      description: "Bukti bebas catatan kriminal. Wajib untuk visa kerja + sebagian PNS.",
      category: "legal",
      required: false,
      issuingAuthority: "POLRI",
      validityYears: 1,
    },
    {
      id: "id-ijazah",
      title: "Ijazah & Transkrip",
      description: "Bukti pendidikan formal. Mungkin perlu legalisir Dikti untuk apply S2 / kerja luar.",
      category: "education",
      required: true,
    },
    {
      id: "id-sertifikat-kompetensi",
      title: "Sertifikat Kompetensi (BNSP)",
      description: "Bukti uji kompetensi profesi. Relevan untuk skilled worker visa.",
      category: "education",
      required: false,
      issuingAuthority: "BNSP",
    },
    {
      id: "id-cv",
      title: "CV / Resume",
      description: "Untuk format internasional (ATS-friendly): no foto, 1 halaman, English. Generate via CV Generator.",
      category: "career",
      required: true,
    },
    {
      id: "id-rekening-koran",
      title: "Rekening Koran 3 bulan",
      description: "Bukti finansial untuk visa + apply sekolah luar.",
      category: "financial",
      required: false,
    },
  ],
};
