import type { SeedCountryDocs } from "./types";

export const JP_DOCS: SeedCountryDocs = {
  country: "JP",
  countryLabel: "Jepang",
  flag: "🇯🇵",
  description: "Dokumen untuk Specified Skilled Worker (SSW), Technical Intern (TITP), atau Engineer/Specialist visa.",
  documents: [
    {
      id: "jp-ssw-cert",
      title: "Sertifikat SSW (lulus ujian)",
      description: "Lulus Japanese Foundation Test (A2) + Skill Specific Test bidang yang relevan.",
      category: "qualification",
      required: true,
      issuingAuthority: "JLPT / Industry Skill Council",
    },
    {
      id: "jp-jlpt-n4",
      title: "JLPT N4 (atau setara)",
      description: "Sertifikat kemampuan bahasa Jepang minimum N4 (A2). N3+ disarankan untuk Engineer visa.",
      category: "language",
      required: true,
      issuingAuthority: "JEES",
      validityYears: 5,
    },
    {
      id: "jp-cert-of-eligibility",
      title: "Certificate of Eligibility (COE / 在留資格認定証明書)",
      description: "Diajukan sponsor di Jepang ke Imigrasi Jepang. WAJIB sebelum apply visa.",
      category: "visa",
      required: true,
      issuingAuthority: "Imigrasi Jepang",
      validityYears: 1,
    },
    {
      id: "jp-passport",
      title: "Paspor (validitas min 18 bulan)",
      description: "Paspor RI dengan masa berlaku lebih lama dari durasi kontrak kerja.",
      category: "travel",
      required: true,
      issuingAuthority: "Imigrasi RI",
    },
    {
      id: "jp-work-visa",
      title: "Visa Kerja (engineering / specialist / SSW)",
      description: "Tempel di paspor setelah COE keluar. Diajukan ke Kedutaan Jepang.",
      category: "visa",
      required: true,
      issuingAuthority: "Kedutaan Jepang",
    },
    {
      id: "jp-ijazah-eng",
      title: "Ijazah & Transkrip (English)",
      description: "Terjemahan resmi ijazah S1 untuk Engineer visa. Min 12 thn pendidikan / S1 STEM.",
      category: "education",
      required: true,
    },
    {
      id: "jp-medical-check",
      title: "Medical Check-up",
      description: "Pemeriksaan kesehatan dari rumah sakit yang direkomendasikan kedutaan.",
      category: "health",
      required: true,
    },
    {
      id: "jp-employment-contract",
      title: "Kontrak Kerja (雇用契約書)",
      description: "Kontrak resmi dari sponsor Jepang. Dasar pengajuan visa + COE.",
      category: "employment",
      required: true,
    },
    {
      id: "jp-resume-japanese",
      title: "Rirekisho (履歴書) + Shokumukeirekisho (職務経歴書)",
      description: "CV format Jepang. Format ketat — foto, hanko/cap nama, urut waktu mundur.",
      category: "career",
      required: true,
    },
    {
      id: "jp-skck-legalized",
      title: "SKCK Legalisir Kedutaan Jepang",
      description: "SKCK dari POLRI + apostille/legalisir Kemenlu + Kedutaan Jepang.",
      category: "legal",
      required: true,
      issuingAuthority: "POLRI + Kemlu RI + Kedutaan Jepang",
      validityYears: 1,
    },
    {
      id: "jp-bank-statement",
      title: "Rekening Koran (jika self-funded)",
      description: "Bukti dana minimal 1.5 juta JPY setara. Hanya untuk student / visa mandiri.",
      category: "financial",
      required: false,
    },
  ],
};
