import type { SeedCountryDocs } from "./types";

export const MY_DOCS: SeedCountryDocs = {
  country: "MY",
  countryLabel: "Malaysia",
  flag: "🇲🇾",
  description: "Dokumen untuk Employment Pass (profesional/skilled) atau PLKS (sektor manufaktur, konstruksi, perkebunan, jasa).",
  documents: [
    {
      id: "my-employment-pass",
      title: "Employment Pass (Kategori I/II/III)",
      description: "Untuk posisi profesional/skilled. Per kebijakan gaji EP terbaru (efektif 1 Jun 2026): Kategori I ≥RM20.000/bln, Kategori II RM10.000–19.999/bln, Kategori III RM5.000–9.999/bln. Tanpa kuota/levy.",
      category: "visa",
      required: true,
      issuingAuthority: "Jabatan Imigresen Malaysia (JIM)",
    },
    {
      id: "my-fwcms",
      title: "Aplikasi FWCMS (Foreign Worker Centralised Management System)",
      description: "Wajib bagi sektor non-profesional (manufaktur, konstruksi, perkebunan, jasa) sejak Feb 2025. Diajukan oleh pemberi kerja.",
      category: "employment",
      required: true,
      issuingAuthority: "Kementerian Sumber Manusia (MOHR)",
    },
    {
      id: "my-passport",
      title: "Paspor (validitas min 12 bulan)",
      description: "Paspor RI dengan sisa masa berlaku minimal 12 bulan saat pengajuan.",
      category: "travel",
      required: true,
      issuingAuthority: "Imigrasi RI",
    },
    {
      id: "my-calling-visa",
      title: "Calling Visa (VDR)",
      description: "Visa dengan Rujukan — diproses lewat perwakilan RI/Malaysia sebelum keberangkatan.",
      category: "visa",
      required: true,
    },
    {
      id: "my-fomema",
      title: "Pemeriksaan Medis FOMEMA",
      description: "Wajib untuk pemegang PLKS, dilakukan dalam 30 hari setelah tiba di Malaysia.",
      category: "health",
      required: true,
      issuingAuthority: "FOMEMA Sdn Bhd",
    },
    {
      id: "my-employment-contract",
      title: "Kontrak Kerja",
      description: "Untuk PRT/pekerja domestik wajib disahkan KBRI/KJRI. Periksa klausa gaji, jam kerja, cuti.",
      category: "employment",
      required: true,
    },
    {
      id: "my-insurance",
      title: "Asuransi SPIKPA",
      description: "Skema Perlindungan Insurans Kesihatan Pekerja Asing — wajib bagi pekerja migran non-profesional.",
      category: "insurance",
      required: true,
    },
    {
      id: "my-plks",
      title: "PLKS / ePLKS (Pas Lawatan Kerja Sementara)",
      description: "Izin kerja sementara, diperbarui tahunan. Levy dibayar pemberi kerja (tidak boleh dipotong dari gaji).",
      category: "visa",
      required: true,
    },
    {
      id: "my-degree",
      title: "Ijazah / Sertifikat Kompetensi",
      description: "Untuk Employment Pass — ijazah min S1 atau sertifikasi kompetensi relevan.",
      category: "education",
      required: false,
    },
    {
      id: "my-resume",
      title: "CV (Bahasa Inggris/Melayu)",
      description: "Untuk jalur profesional — format ATS-friendly, cantumkan pengalaman terukur.",
      category: "career",
      required: false,
    },
  ],
  sources: [
    { label: "Jabatan Imigresen Malaysia — Expatriate Services Division", url: "https://esd.imi.gov.my/portal/" },
    { label: "Kementerian Sumber Manusia Malaysia (MOHR)", url: "https://www.mohr.gov.my/" },
    { label: "FWCMS — portal pekerja asing", url: "https://fwcms.mohr.gov.my/" },
    { label: "FOMEMA — pemeriksaan medis wajib", url: "https://www.fomema.com.my/" },
  ],
  lastVerified: "2026-08-31",
};
