import type { SeedCountryDocs } from "./types";

export const NL_DOCS: SeedCountryDocs = {
  country: "NL",
  countryLabel: "Belanda",
  flag: "🇳🇱",
  description: "Dokumen untuk Highly Skilled Migrant, Orientation Year (zoekjaar), atau StuNed scholarship.",
  documents: [
    {
      id: "nl-ielts-toefl",
      title: "IELTS 6.5+ / TOEFL iBT 80+",
      description: "Bukti bahasa Inggris. Wajib untuk studi + sebagian kontrak kerja MNC di Belanda.",
      category: "language",
      required: true,
    },
    {
      id: "nl-hsm-contract",
      title: "Kontrak Highly Skilled Migrant",
      description: "Sponsor harus IND-recognised. Min gaji €5.688/bln (under 30 thn) atau €4.171 fresh graduate.",
      category: "employment",
      required: false,
    },
    {
      id: "nl-zoekjaar",
      title: "Orientation Year Permit (Zoekjaar)",
      description: "Untuk fresh graduate top-200 univ + lulusan Belanda. Valid 12 bln cari kerja.",
      category: "visa",
      required: false,
      issuingAuthority: "IND",
      validityYears: 1,
    },
    {
      id: "nl-stuned",
      title: "Letter of Acceptance + StuNed/Beasiswa",
      description: "Untuk jalur study-to-work. Letter dari univ Belanda + dana beasiswa NEC StuNed.",
      category: "education",
      required: false,
    },
    {
      id: "nl-mvv",
      title: "MVV (Provisional Residence Permit)",
      description: "Stempel di paspor di Kedutaan Belanda di Jakarta. Wajib sebelum berangkat.",
      category: "visa",
      required: true,
      issuingAuthority: "Kedutaan Belanda",
    },
    {
      id: "nl-passport",
      title: "Paspor (validitas min 6 bulan lebih lama dari kontrak)",
      description: "Paspor RI.",
      category: "travel",
      required: true,
      issuingAuthority: "Imigrasi RI",
    },
    {
      id: "nl-bsn",
      title: "Burger Service Nummer (BSN)",
      description: "Nomor identitas Belanda. Daftar di gemeente setelah datang. Wajib untuk bank + pajak.",
      category: "identity",
      required: true,
      issuingAuthority: "Gemeente",
    },
    {
      id: "nl-zorgverzekering",
      title: "Asuransi Kesehatan (Zorgverzekering)",
      description: "Wajib dalam 4 bulan setelah masuk Belanda. ~€140/bulan.",
      category: "insurance",
      required: true,
    },
    {
      id: "nl-diploma-nuffic",
      title: "Diploma Evaluation (NUFFIC)",
      description: "Cek apakah ijazah ID = Bachelor/Master setara NL. Untuk visa kerja.",
      category: "education",
      required: true,
      issuingAuthority: "NUFFIC",
    },
    {
      id: "nl-resume-english",
      title: "CV (English, format internasional)",
      description: "Max 2 halaman, no foto, ATS-friendly. Generate via CV Generator.",
      category: "career",
      required: true,
    },
    {
      id: "nl-bank-statement",
      title: "Rekening Koran 3 bulan",
      description: "Bukti dana minimal hidup 1 bulan + tiket pulang.",
      category: "financial",
      required: false,
    },
  ],
};
