import type { SeedCountryDocs } from "./types";

export const SA_DOCS: SeedCountryDocs = {
  country: "SA",
  countryLabel: "Arab Saudi",
  flag: "🇸🇦",
  description: "Dokumen untuk Saudi Work Visa, Premium Residency, atau Domestic Worker (PMI sektor informal).",
  documents: [
    {
      id: "sa-work-visa",
      title: "Saudi Work Visa (issued via Enjazit)",
      description: "Sponsor (kafil) urus melalui platform Enjazit + MOL Saudi.",
      category: "visa",
      required: true,
      issuingAuthority: "MOL Saudi Arabia",
    },
    {
      id: "sa-iqama",
      title: "Iqama (Residence Permit)",
      description: "ID resident Saudi. Diterbitkan oleh Jawazat setelah datang. Wajib untuk semua urusan.",
      category: "identity",
      required: true,
      issuingAuthority: "Jawazat",
      validityYears: 1,
    },
    {
      id: "sa-passport",
      title: "Paspor (validitas min 6 bulan)",
      description: "Paspor RI dengan halaman kosong cukup.",
      category: "travel",
      required: true,
      issuingAuthority: "Imigrasi RI",
    },
    {
      id: "sa-medical-gamca",
      title: "GAMCA Medical Check-up",
      description: "Medical wajib di klinik approved GCC sebelum visa keluar.",
      category: "health",
      required: true,
      issuingAuthority: "GAMCA-approved clinic",
    },
    {
      id: "sa-attestation-mofa",
      title: "Attestasi Dokumen (MOFA Saudi)",
      description: "Ijazah + kontrak + SKCK harus di-attest oleh Kemlu RI + Kedutaan Saudi + MOFA Saudi.",
      category: "legal",
      required: true,
      issuingAuthority: "MOFA Saudi",
    },
    {
      id: "sa-employment-contract",
      title: "Employment Contract (Arabic + English)",
      description: "Dual-language wajib. Klausa upah, jam kerja, end-of-service gratuity (1 bulan/tahun).",
      category: "employment",
      required: true,
    },
    {
      id: "sa-bp2mi",
      title: "Dokumen BP2MI (kalau via P3MI)",
      description: "Untuk PMI domestik dan beberapa sektor lain — verifikasi BP2MI wajib.",
      category: "employment",
      required: false,
      issuingAuthority: "BP2MI",
    },
    {
      id: "sa-degree-attest",
      title: "Ijazah + Apostille + Saudi MOFA",
      description: "Apostille Kemlu + Kedutaan Saudi + MOFA Riyadh / Jeddah.",
      category: "education",
      required: true,
    },
    {
      id: "sa-resume-english-arabic",
      title: "CV (English; Arabic versi untuk sektor pemerintah)",
      description: "Format internasional. Khusus pemerintah Saudi tambahkan versi Arabic.",
      category: "career",
      required: true,
    },
    {
      id: "sa-bank-account",
      title: "Rekening Bank Saudi",
      description: "Dibuat setelah Iqama keluar.",
      category: "financial",
      required: true,
    },
  ],
};
