import type { SeedCountryDocs } from "./types";

export const SG_DOCS: SeedCountryDocs = {
  country: "SG",
  countryLabel: "Singapura",
  flag: "🇸🇬",
  description: "Dokumen untuk Employment Pass (EP), S Pass, atau Tech.Pass (untuk top tech talent).",
  documents: [
    {
      id: "sg-employment-pass",
      title: "Employment Pass Application (IPA)",
      description: "Diajukan sponsor SG ke MOM. Min gaji S$5.000/bln (S$5.500 untuk financial sector).",
      category: "visa",
      required: true,
      issuingAuthority: "Ministry of Manpower (MOM)",
    },
    {
      id: "sg-cocsa-points",
      title: "COMPASS Score ≥ 40 poin",
      description: "Wajib sejak Sep 2023. Skor dari gaji, kualifikasi, diversitas, dukungan lokal.",
      category: "qualification",
      required: true,
    },
    {
      id: "sg-degree",
      title: "Ijazah S1+ dari univ ter-akreditasi",
      description: "EP butuh top global ranking; akreditasi WES atau sebanding membantu.",
      category: "education",
      required: true,
    },
    {
      id: "sg-passport",
      title: "Paspor (validitas min 6 bulan)",
      description: "Paspor RI.",
      category: "travel",
      required: true,
      issuingAuthority: "Imigrasi RI",
    },
    {
      id: "sg-medical-check",
      title: "Medical Check-up Singapore",
      description: "Cek di SG dalam 3 bulan setelah datang. TB chest X-ray + HIV.",
      category: "health",
      required: true,
    },
    {
      id: "sg-fin",
      title: "FIN (Foreign Identification Number)",
      description: "Diberikan saat EP / S Pass terbit. ID untuk semua urusan di SG.",
      category: "identity",
      required: true,
      issuingAuthority: "MOM",
    },
    {
      id: "sg-resume-english",
      title: "CV (English, ATS-friendly)",
      description: "Format internasional, no foto, max 2 halaman. Highlight skor COMPASS-friendly.",
      category: "career",
      required: true,
    },
    {
      id: "sg-cpf",
      title: "CPF (Central Provident Fund)",
      description: "Bagi PR / SC saja. EP holder tidak wajib CPF. Untuk reference kemudian hari.",
      category: "financial",
      required: false,
    },
    {
      id: "sg-tax",
      title: "IRAS Tax Number",
      description: "Auto-issued setelah EP terbit. Wajib filing pajak Apr setiap tahun.",
      category: "financial",
      required: true,
      issuingAuthority: "IRAS",
    },
    {
      id: "sg-employment-contract",
      title: "Letter of Offer + Employment Contract",
      description: "Pastikan klausa gaji + benefits cocok dengan IPA approval.",
      category: "employment",
      required: true,
    },
  ],
};
